### ISSUE TITLE
Reference to missing testutils/network.yml

### ISSUE THREAD

**Issue by konklone** [getcloudless/cloudless#53]
This is the error message I got (on both Python 3.6 and 3.7) when testing out cloudless last night.

Command:

```
$ cldls image-build deploy examples/base-image/aws_image_build_configuration.yml
```

Result:

```
image group with provider: aws
Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/3.6.4/bin/cldls", line 11, in <module>
    sys.exit(main())
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/cli/main.py", line 12, in main
    cldls_cli()
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/cli/image_build.py", line 42, in image_build_deploy
    service, state = image_builder.deploy()
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/testutils/image_builder.py", line 136, in deploy
    network = self.client.network.create(state["network"], NETWORK_BLUEPRINT)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/network.py", line 44, in create
    return self.network.create(name, blueprint)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/providers/aws/network.py", line 25, in create
    return self.network.create(name, blueprint)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/providers/aws/impl/network.py", line 44, in create
    network_blueprint = NetworkBlueprint.from_file(blueprint)
  File "/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/util/blueprint.py", line 47, in from_file
    with open(blueprint_filename, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/eric/.pyenv/versions/3.6.4/lib/python3.6/site-packages/cloudless/testutils/network.yml'
```

**Comment by sverch** [comment]
This actually only comes up when running the AWS commands, since they actually read that file, which explains why I didn't hit it before.
